# ============================================================
# FILE: platform-config-repo/apps/prod/payment-service.yaml
# PURPOSE: Tells Argo CD HOW to deploy payment-service to PROD
# ============================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service-prod
  namespace: argocd
  labels:
    app: payment-service
    environment: prod
spec:
  project: prod-project
  source:
    repoURL: git@gitlab.company.com:platform/platform-config-repo.git
    targetRevision: main
    path: helm-charts/generic-service
    helm:
      valueFiles:
        - values.yaml
        - ../../clusters/prod/payment-service/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-payment-service
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
