serviceName: order-service
environment: prod

image:
  repository: 333333333333.dkr.ecr.us-east-1.amazonaws.com/order-service
  tag: "ghi9012"
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 12
  targetCPUUtilizationPercentage: 60

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::333333333333:role/prod-order-service-irsa

podDisruptionBudget:
  enabled: true
  minAvailable: 2

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values: ["order-service"]
        topologyKey: topology.kubernetes.io/zone
